import Head from 'next/head';
import Image from 'next/image';
import Banner from '../components/banner';
import Card from '../components/card';
import { fetchCoffeeStores } from '../lib/coffee-stores';
import styles from '../styles/Home.module.css';

// import coffeeStoresData from '../data/coffee-stores.json';

export default function Home(props) {
  const handleOnBtnClick = () => {
    console.log('hi button banner');
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText="View stores nearby"
          handleOnClick={handleOnBtnClick}
        />
        <div className={styles.heroImage}>
          <Image src="/static/hero-image.png" width={700} height={400} />
        </div>
        <br />
        <br />
        <br />
        <br />
        {props.coffeeStores.length > 0 && (
          <>
            <h2 className={styles.heading2}>Toronto Stores</h2>
            <div className={styles.cardLayout}>
              {props.coffeeStores.map((coffeeStore) => {
                return (
                  <Card
                    key={coffeeStore.fsq_id}
                    name={coffeeStore.name}
                    imgUrl={coffeeStore.imgUrl ||  "https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2000&q=80"}
                    href={`coffee-store/${coffeeStore.id}`}
                    className={styles.card}
                  />
                );
              })}
            </div>
          </>
        )}
      </main>
    </div>
  );
}

export async function getStaticProps(context) {
 
  const coffeeStores =  await fetchCoffeeStores();



  return {
    props: {
      coffeeStores,
    }
  }
};







// const coffeeStores = await fetchCoffeeStores();

//   return data.results?.map((venue, idx) => {
//     const neighbourhood = venue.location.neighborhood;
    
//     return {
//       props: {
//         coffeeStores,
//       }
      
//     };
//   }
  // );
  // const transformedData =
  //   data?.results?.map((venue) => {
  //     return {
  //       id: venue.fsq_id,
  //       ...venue,
  //     };
  //   }) || [];

  // console.log(transformedData);

  // return {
  //   props: {
  //     coffeeStores: data.response.venues,
  //   },
  // };

